version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "no"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=square
    - POSTGRES_PASSWORD=qwer1234
    - POSTGRES_DB=test
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    - ./pginit:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    container_name: redis
    restart: "no"
    ports:
    - "6379:6379"
    volumes:
    - ./conf:/usr/local/etc/redis
    - ./redisdata:/data
    command: redis-server /usr/local/etc/redis/redis.conf
