version: '3'
services:
  db:
      image: postgres:latest
      container_name: db
      restart: "no"
      ports:
      - "5432:5432"
      environment:
      - POSTGRES_USER=square
      - POSTGRES_PASSWORD=qwer1234
      - POSTGRES_DB=test
      volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pginit:/docker-entrypoint-initdb.d/
